version: '3.8'

volumes:
    php-fpm-socket:
    db-volumes:

services:
    app:
        build: ./docker/app
        volumes:
            - type: bind
              source: ./src
              target: /var/www/src
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true
        environment:
            - TZ=Asia/Tokyo
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - type: bind
              source: ./src
              target: /var/www/src
            - type: bind
              source: ./docker/nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true

    db:
        build: ./docker/db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        volumes:
            - db-volumes:/var/lib/mysql
            - ./docker/db/sql:/docker-entrypoint-initdb.d
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./tmp:/var/log/mysql
        ports:
            - 3306:3306
